=== prettyHello/INFO-H509-XML/Project1_XML_Schema_Definition/bookshop_xml_shema.xsd
<?xml version="1.0" encoding="UTF-8"?>



<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<!-- balises attribute "Type"  -->

	<xsd:attribute name="type">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="scientific"/>
				<xsd:enumeration value="leisure"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>
	
	<!-- balises attribute "genre"  -->
	
	<xsd:attribute name="genre">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="thriller"/>
				<xsd:enumeration value="horror"/>
				<xsd:enumeration value="sci/fi"/>
				<xsd:enumeration value="romance"/>
				<xsd:enumeration value="literature"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>

	<!-- balises independante  -->
	<!-- ################################################################################################ -->	
	<xsd:element name="titre" type="xsd:string"/>
	<xsd:element name="publisher" type="xsd:string"/>
	<xsd:element name="edition" type="xsd:string"/>
	<xsd:element name="YearPublication" type="xsd:gYear"/>
	
	<!--************  -->
	<xsd:element name="name" type="xsd:string"/>
	<xsd:element name="FirstName" type="xsd:string"/>
	
	<!--************  -->	
	<xsd:element name="numero" type="xsd:string"/>
	<xsd:element name="rue" type="xsd:string"/>
	<xsd:element name="city" type="xsd:string"/>
	<xsd:element name="country" type="xsd:string"/>
	
	<!--************  -->	
	<xsd:element name="PostalCode">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="[0-9]{4}"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	
	<!--************  -->	
	<!-- <xsd:element name="Phone"> -->
		<xsd:complexType name="PHONE">
			<xsd:simpleContent>	
			<xsd:extension base="xsd:string"> 
				<xsd:attribute name="type" use="required"> <xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="HousePhone"/>
							<xsd:enumeration value="cellphone"/>
							<xsd:enumeration value="OfficePhone"/>
						</xsd:restriction> </xsd:simpleType>
				</xsd:attribute>
				<xsd:attribute name="locality" use="optional"> <xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:pattern value="[A-Z]{3}"/>
							<xsd:enumeration value="BEL"/>
							<xsd:enumeration value="CMR"/>
							<xsd:enumeration value="USA"/>
						</xsd:restriction> </xsd:simpleType>
				</xsd:attribute>	
			</xsd:extension> 
			</xsd:simpleContent>
		</xsd:complexType>
	<!-- </xsd:element>  -->
	
<!--************  -->

	<!-- <xsd:element name="email"> -->
		<xsd:complexType name="EMAIL">
			<xsd:simpleContent>
			<xsd:extension base="xsd:string">  
				<xsd:attribute name="type" default="personnel">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="personnel"/>
							<xsd:enumeration value="professionnel"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
				</xsd:extension> 
			</xsd:simpleContent>
		</xsd:complexType>
	<!-- </xsd:element> -->
	
<!-- ################################################################################################ -->
	
	<!-- balise Email -->

	<xsd:element name="emails">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="email" type="EMAIL" minOccurs="1" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<!-- balises de l'adresse  -->
	
	<xsd:element name="adresse">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="numero"/>
				<xsd:element ref="rue"/>
				<xsd:element ref="PostalCode"/>
				<xsd:element ref="city"/>
				<xsd:element ref="country"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<!-- balise telephone -->
	
	<xsd:element name="Phones">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Phone" type="PHONE" minOccurs="1" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<!-- balises person -->
	
	<xsd:element name="person">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="name"/>
				<xsd:element ref="FirstName"/>
				<xsd:element ref="adresse"/>
				<xsd:element ref="Phones"/>
				<xsd:element ref="emails"/>
			</xsd:sequence>
			<xsd:attribute name="sexe">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:length value="1"/>
						<xsd:enumeration value="M"/>
						<xsd:enumeration value="F"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	
	<!-- balises auteurs -->
	
	<xsd:element name="authors">
		<xsd:complexType>
			<xsd:all>
				<xsd:element ref="person"/>
			</xsd:all>
		</xsd:complexType>
	</xsd:element>
	
	<!-- balises article -->
	
	<xsd:element name="article" >
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="titre"/>
				
				<xsd:element name="ListingPerson">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element ref="authors" minOccurs="1" maxOccurs="unbounded"/>
					</xsd:sequence>
				</xsd:complexType>	
				</xsd:element>
				

				<xsd:choice>
					<xsd:element name="NumPage">
						<xsd:complexType>
							<xsd:sequence>
								<xsd:element name="StartPage" type="xsd:positiveInteger"/>
								<xsd:element name="EndPage" type="xsd:positiveInteger"/>
							</xsd:sequence>
						</xsd:complexType>
					</xsd:element>
					<xsd:element name="NumArticle" type="xsd:positiveInteger"/>
				</xsd:choice>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<!-- balises journals -->
	
	<xsd:element name="journals">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="titre"/>
				<xsd:element name="volume" type="xsd:string" />
				<xsd:element name="number" type="xsd:nonNegativeInteger" />
				<xsd:element name="ListingPerson">
				<xsd:complexType>
					<xsd:choice>
						<xsd:element ref="authors" minOccurs="1" maxOccurs="unbounded"/>
						<xsd:element name="NumRedactor" type="xsd:positiveInteger" />
					</xsd:choice>
				</xsd:complexType>	
				</xsd:element>
				<xsd:element ref="YearPublication"/>
				<xsd:element ref="publisher" minOccurs="0" maxOccurs="1" />
				<xsd:element name="ImpactFactor" minOccurs="0" maxOccurs="1">
					<xsd:complexType>
						<xsd:simpleContent>
							<xsd:extension base="xsd:string">
								<xsd:attribute name="Year" type="xsd:gYear" />
							</xsd:extension>
						</xsd:simpleContent>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="contents">
					<xsd:complexType>
						<xsd:all>
							<xsd:element ref="article"/>
						</xsd:all>
					</xsd:complexType>
				</xsd:element>
				
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="book">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="titre"/>
				<xsd:element name="ListingPerson">
					<xsd:complexType>
						<xsd:choice>
							<xsd:element ref="authors" minOccurs="1" maxOccurs="unbounded"/>
							<xsd:element ref="publisher" minOccurs="1" maxOccurs="unbounded" />
						</xsd:choice>
					</xsd:complexType>	
				</xsd:element>
				<xsd:element ref="publisher" />
				<xsd:element ref="YearPublication" />
				<xsd:element name="abstract" type="xsd:string" minOccurs="0" />
				<xsd:element ref="edition" minOccurs="0" />
				<xsd:element name="Num_page"  type="xsd:positiveInteger" minOccurs="0" />
			</xsd:sequence>
			<xsd:attribute ref="type" use="required"/>
			<xsd:attribute name="isbn" type="xsd:string" use="optional"/>
			<xsd:attribute ref="genre" use="optional"/>
		</xsd:complexType>
	</xsd:element>
	
	
	<xsd:element name="periodicals">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="titre" />
				<xsd:element name="price">
					<xsd:complexType>
						<xsd:simpleContent>
							<xsd:extension base="xsd:positiveInteger">
								<xsd:attribute name="currency"  >
									<xsd:simpleType>
										<xsd:restriction base="xsd:string">
											<xsd:enumeration value="EURO"/>
											<xsd:enumeration value="DOL"/>
											<xsd:enumeration value="XAF"/>
										</xsd:restriction>
									</xsd:simpleType>
								</xsd:attribute>
							</xsd:extension>
						</xsd:simpleContent>
					</xsd:complexType>
				</xsd:element>
				<xsd:element ref="publisher" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
		<xsd:element name="booksss">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="titre"/>
				<xsd:element name="ListingPerson">
					<xsd:complexType> 
						<xsd:sequence>
							<xsd:element ref="authors" minOccurs="1" maxOccurs="unbounded"/>
						</xsd:sequence>
					</xsd:complexType>	
				</xsd:element>
				<xsd:element ref="publisher" />
				<xsd:element ref="YearPublication" />
				<xsd:element ref="edition" minOccurs="0" />
				<xsd:element name="Num_page"  type="xsd:positiveInteger" minOccurs="0" />
			</xsd:sequence>
			<xsd:attribute ref="type"/>
			

		</xsd:complexType>
	</xsd:element>
	
	
	
	<!-- ######### balises PRINCIPAL ##############-->
	
	<xsd:element name="bookshop">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="ScientificProducts">
					<xsd:complexType>
						<xsd:all>
							<xsd:element ref="book"/>
							<xsd:element ref="journals"/>
						</xsd:all>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="LeisureProducts">
					<xsd:complexType>
						<xsd:all>
							<xsd:element ref="book"/>
							<xsd:element ref="periodicals"/>
						</xsd:all>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>	
	</xsd:element>

</xsd:schema>

=== prettyHello/INFO-H509-XML/Project1_XML_Schema_Definition/bookshop.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<bookshop xsi:noNamespaceSchemaLocation="bookshop_xml_shema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<ScientificProducts>
		<book type="scientific" isbn="h-78">
			<title> Cybersecurity</title>
			<ListingAuthors>
				<authors ID="P1">
					<person sexe="M">
						<name>Siewe</name>
						<FirstName>Anicet</FirstName>
						<adresse>
							<numero>7</numero>
							<rue>impasse du chemin</rue>
							<PostalCode>7505</PostalCode>
							<city>Bruxelle</city>
							<country>Belgique</country>
						</adresse>
						<Phones>
							<Phone type="HousePhone" locality="BEL">03265765675675</Phone>
							<Phone type="cellphone" locality="BEL">03265765765675</Phone>
							<Phone type="OfficePhone" locality="BEL">0325865675</Phone>
						</Phones>
						<emails>
							<email type="personnel">asiewekoulbacbe</email>
							<email type="professionnel">asieweko@ulb.ac.be</email>
						</emails>
					</person>
				</authors>
			</ListingAuthors>
			<publisher>ULB</publisher>
			<YearPublication>2016</YearPublication>
			<abstract>Cryptography Systems and Networks Legal, ethics, and human aspects Management of the Security Secure software engineering</abstract>
			<edition>edition NATAN</edition>
		</book>
		<journals>
			<title> RESEARCH LABS</title>
			<volume>67</volume>
			<number>7654</number>
			<ListingAuthors>
				<authors ID="drt">
					<person sexe="M">
						<name>DOE</name>
						<FirstName>John</FirstName>
						<adresse>
							<numero>7</numero>
							<rue>impasse du chemin</rue>
							<PostalCode>7515</PostalCode>
							<city>PARIS</city>
							<country>FRANCE</country>
						</adresse>
						<Phones>
							<Phone type="HousePhone" locality="BEL">03265765675675</Phone>
							<Phone type="cellphone" locality="BEL">0325865675</Phone>
							<Phone type="OfficePhone" locality="BEL">0325865675</Phone>
						</Phones>
						<emails>
							<email type="personnel">asieweko@ulb.ac.be</email>
							<email type="professionnel">asieweko@ulb.ac.be</email>
						</emails>
					</person>
				</authors>
			</ListingAuthors>
			<YearPublication>2019</YearPublication>
			<publisher>Nom de l'editeur</publisher>
			<ImpactFactor Year="2019"> Type pas encorre connue</ImpactFactor>
			<contents>
				<article>
					<title> Article 1</title>
					<ListingAuthors>
						<authors ID="eds">
							<person sexe="M">
								<name>Anicet</name>
								<FirstName>Siewe</FirstName>
								<adresse>
									<numero>7</numero>
									<rue>impasse du chemin</rue>
									<PostalCode>7515</PostalCode>
									<city>Bruxelle</city>
									<country>Belgique</country>
								</adresse>
								<Phones>
									<Phone type="HousePhone" locality="BEL">03265765675675</Phone>
									<Phone type="cellphone" locality="BEL">03265765675675</Phone>
									<Phone type="OfficePhone" locality="BEL">0325865675</Phone>
								</Phones>
								<emails>
									<email type="personnel">asieweko@ulb.ac.be</email>
									<email type="professionnel">asieweko@ulb.ac.be</email>
								</emails>
							</person>
						</authors>
					</ListingAuthors>
					<NumPage>
						<StartPage>45</StartPage>
						<EndPage>100</EndPage>
						<!-- <NumArticle>56</NumArticle> -->
					</NumPage>
				</article>
			</contents>
		</journals>
	</ScientificProducts>
	<LeisureProducts>
		<book type="leisure" genre="thriller">
			<title> Teste du title du livre</title>
			<ListingAuthors>
						<authors ID="PTs">
							<person sexe="M">
								<name>Anicet</name>
								<FirstName>Siewe</FirstName>
								<adresse>
									<numero>7</numero>
									<rue>impasse du chemin</rue>
									<PostalCode>7515</PostalCode>
									<city>Bruxelle</city>
									<country>Belgique</country>
								</adresse>
								<Phones>
									<Phone type="HousePhone" locality="BEL">03265765675675</Phone>
									<Phone type="cellphone" locality="BEL">03265765675675</Phone>
									<Phone type="OfficePhone" locality="BEL">0325865675</Phone>
								</Phones>
								<emails>
									<email type="personnel">asieweko@ulb.ac.be</email>
									<email type="professionnel">asieweko@ulb.ac.be</email>
								</emails>
							</person>
						</authors>
					</ListingAuthors>
			<publisher>Nom de l'editeur</publisher>
			<YearPublication>2017</YearPublication>
			<edition>edition NATAN</edition>
			<PageNum>56</PageNum>
		</book>
		<periodicals>
			<title> Teste du title du livre</title>
			<price currency="EURO">300</price>
			<publisher>Nom de l'editeur</publisher>
		</periodicals>
	</LeisureProducts>
</bookshop>

=== prettyHello/INFO-H509-XML/Project1_XML_Schema_Definition/bookshop2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<bookshop xsi:noNamespaceSchemaLocation="bookshop_xml_shema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<ScientificProducts>
		<book type="scientific" isbn="h-78">
			<titre> Teste du titre du libre</titre>
			<ListingEditors>
				<editor ID="P1">
						<name>anicet</name>
						<adresse>
							<numero>134</numero>
							<rue>Avenue de l'universite</rue>
							<PostalCode>1050</PostalCode>
							<city>bruxelle</city>
							<country>Belgique</country>
						</adresse>
						<Phones>
							<Phone type="HousePhone" locality="BEL">03265765675675</Phone>
							<Phone type="cellphone" locality="BEL">03265765765675</Phone>
							<Phone type="OfficePhone" locality="BEL">0325865675</Phone>
						</Phones>
						<emails>
							<email type="personnel">asiewekoulbacbe</email>
							<email type="professionnel">asieweko@ulb.ac.be</email>
						</emails>
				</editor>
			</ListingEditors>
			<publisher>Nom de l'editeur</publisher>
			<YearPublication>2019</YearPublication>
		</book>
		<journals>
			<titre> titre du Jounal</titre>
			<volume>67</volume>
			<number>7654</number>
			<NumRedactor>756</NumRedactor>
			<YearPublication>2019</YearPublication>
			<contents>
				<article>
					<titre> titre du Jounal</titre>
					<ListingAuthors>
						<authors ID="eds">
							<person sexe="M">
								<name>DOE</name>
								<FirstName>John</FirstName>
								<adresse>
									<numero>7</numero>
									<rue>impasse du chemin</rue>
									<PostalCode>7515</PostalCode>
									<city>PARIS</city>
									<country>FRANCE</country>
								</adresse>
								<Phones>
									<Phone type="HousePhone" locality="BEL">03265765675675</Phone>
									<Phone type="cellphone" locality="BEL">03265765675675</Phone>
									<Phone type="OfficePhone" locality="BEL">0325865675</Phone>
								</Phones>
								<emails>
									<email type="personnel">asieweko@ulb.ac.be</email>
									<email type="professionnel">asieweko@ulb.ac.be</email>
								</emails>
							</person>
						</authors>
					</ListingAuthors>

					<NumArticle>56</NumArticle>
				</article>
			</contents>
		</journals>
	</ScientificProducts>
	<LeisureProducts>
		<book type="leisure" genre="literature">
			<titre> Teste du titre du livre</titre>
			<ListingAuthors>
						<authors ID="PTs">
							<person sexe="M">
								<name>DOE</name>
								<FirstName>John</FirstName>
								<adresse>
									<numero>7</numero>
									<rue>impasse du chemin</rue>
									<PostalCode>7515</PostalCode>
									<city>PARIS</city>
									<country>FRANCE</country>
								</adresse>
								<Phones>
									<Phone type="HousePhone" locality="BEL">03265765675675</Phone>
									<Phone type="cellphone" locality="BEL">03265765675675</Phone>
									<Phone type="OfficePhone" locality="BEL">0325865675</Phone>
								</Phones>
								<emails>
									<email type="personnel">asieweko@ulb.ac.be</email>
									<email type="professionnel">asieweko@ulb.ac.be</email>
								</emails>
							</person>
						</authors>
					</ListingAuthors>
			<publisher>Nom de l'editeur</publisher>
			<YearPublication>2019</YearPublication>

		</book>
		<periodicals>
			<titre> Teste du titre du livre</titre>
			<price currency="XAF">3500</price>
			<publisher>Nom de l'editeur</publisher>
		</periodicals>
	</LeisureProducts>
</bookshop>
